// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using GG_Webbshop;
//
//    var allProductsResponseModel = AllProductsResponseModel.FromJson(jsonString);

namespace GG_Webbshop
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class AllProductsResponseModel
    {
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("price")]
        public double Price { get; set; }

        [JsonProperty("weight")]
        public long Weight { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("createDate")]
        public DateTimeOffset CreateDate { get; set; }

        [JsonProperty("stock")]
        public long Stock { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("brand")]
        public string Brand { get; set; }
    }

    public partial class AllProductsResponseModel
    {
        public static AllProductsResponseModel[] FromJson(string json) => JsonConvert.DeserializeObject<AllProductsResponseModel[]>(json, GG_Webbshop.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this AllProductsResponseModel[] self) => JsonConvert.SerializeObject(self, GG_Webbshop.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
